services:
    toys:
      build:
        context: .
        dockerfile: ./apps/toys/Dockerfile
        target: development
      command: pnpm start:dev
      env_file:
        - ./apps/toys/.env
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 3000:3000
      networks:
        - backend
      depends_on:
        - rabbitmq
        - redis

    auth:
      build:
        context: .
        dockerfile: ./apps/auth/Dockerfile
        target: development
      command: pnpm start:dev auth
      env_file:
        - ./apps/auth/.env
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 3001:3001
      networks:
        - backend
      depends_on:
        - rabbitmq
        - redis

    files:
      build:
        context: .
        dockerfile: ./apps/files/Dockerfile
        target: development
      command: pnpm start:dev files
      env_file:
        - ./apps/files/.env
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 3002:3002
      networks:
        - backend
      depends_on:
        - rabbitmq
        - redis

    rabbitmq:
      image: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - backend

    redis:
      image: redis:latest
      command: redis-server --port 6379
      ports:
        - 6379:6379
      networks:
        - backend

    kong:
      build:
        context: ./kong
        dockerfile: Dockerfile
      restart: unless-stopped
      ports:
        - "8000:8000"
        - "8001:8001"
        - "8443:8443"
      networks:
        - backend
      logging:
        driver: fluentd
        options:
          fluentd-async: "true"
          fluentd-address: localhost:24224
          tag: kong


networks:
  backend:
    driver: bridge
